name: Deploy Supabase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Link & Deploy Supabase (via npx)
        run: |
          npx supabase@latest link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
          npx supabase@latest db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
